### PR TITLE
Fix GLES build not working

### LINKED ISSUE #11: example3 and example4 require GL linking
OS: Linux

This happens when both shared and examples CMake options are enabled. 
`NANOGUI_EXTRA_LIB` has been set to PRIVATE but example3 and example4 still need GL linking.  One solution is setting `NANOGUI_BUILD_GLAD` to `ON`. Maybe the default options for Linux need a change, or set `NANOGUI_EXTRA_LIB` back to PUBLIC.

### PR DESCRIPTION
**Pull request by cyclopsian**
I was running into some compile errors using the GLES backends:

- missing `GL_UNPACK_` defines in GLES2
- missing GLES variants of the imageview shaders
- references to `Shader::m_uses_point_size` which is only defined in OpenGL
- linking to incorrect libraries on Linux/BSD (in mesa/libglvnd there is no libGLESv3, it's all in libGLESv2)

This should fix them all, it should also fix #11, but please test that before merging.

### CODE REVIEW

File: src/texture_gl.cpp [hunk 1]
```diff
@@ -157,9 +157,17 @@ void Texture::upload(const uint8_t *data) {
 
         if (data) {
             CHK(glPixelStorei(GL_UNPACK_ALIGNMENT, 1));
+#if defined(NANOGUI_USE_GLES) && NANOGUI_GLES_VERSION == 2
+            if (glfwExtensionSupported("GL_EXT_unpack_subimage")) {
+              CHK(glPixelStorei(GL_UNPACK_ROW_LENGTH_EXT, 0));
```
Comment (wjakob) [inline src/texture_gl.cpp]: 4-space indent.

**Comment by wjakob** [comment]
Hi @cyclopsian,

cool, thank you very much for fixing that!! I had just a super-minor comment regarding the code formatting.

Best,
Wenzel

**Comment by wjakob** [comment]
Thanks!
